### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ReyFox** [madk/LoLAccountChecker#2]
If an account gives back an error, or it couldn't login, i think its pointless tosave it to the log.
Example for error:
Error: Unable to get Auth Key 
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PVPNetConnect.TypedObject.GetInt(String key)
   at PVPNetConnect.PVPNetConnection.GetAuthKey()

**Comment by madk** [comment]
Fixed.
