### ISSUE TITLE
Suggestion:Refunds and Avaliable transfers

### ISSUE THREAD

**Issue by svenxxl** [madk/LoLAccountChecker#35]
Can you make a tab for check if the accounts has free transfer and if the account has  to where?  
Also if it has avaliable refunds.

Thanks for ur nice work :)

**Comment by unSatisfied9** [comment]
Recommend this under the PVPNetConnect repository, since that's the project that gets the data from the summoner's account.

**Comment by madk** [comment]
We can do it without changing anything in the PVPNetConnect since we can access the store.

**Comment by ReyFox** [comment]
This is a really good idea :P

**Comment by madk** [comment]
Add in 23a5aa428f02b3bcbe277e9d4fe1ad2d4adc001a and bdcd5ad8ce897c1149c5f04219a89e35fc32260a

**Comment by madk** [comment]
I will leave this open since i didn't test the transfers, my account don't have any transfer free.

**Comment by svenxxl** [comment]
I get this crash error on the new version that i compiled  with the transfers etc
It occurs when i add accounts through a text file,doesnt occur if add them manually (1 by 1) :

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LoLAccountChecker.Utils.GetLogins(String file) in c:\Users\Tony\Desktop\LoLAccountChecker-master\Utils.cs:line 58
   at LoLAccountChecker.Views.AccountsWindow.BtnImportClick(Object sender, RoutedEventArgs e) in c:\Users\Tony\Desktop\LoLAccountChecker-master\Views\AccountsWindow.xaml.cs:line 77
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by madk** [comment]
Fixed in fb2cdd73be59e096b505bf748c8d97205b999852

**Comment by svenxxl** [comment]
If you try checking an account with avaliable transfers u get the following error ( coppied directly from the error log) : 

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: i
   at System.Text.RegularExpressions.MatchCollection.get_Item(Int32 i)
   at LoLAccountChecker.Client.<GetStoreData>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at LoLAccountChecker.Client.<GetData>d__3.MoveNext()

**Comment by madk** [comment]
Could you contact me via [Nulled.io](http://www.nulled.io/user/3198-madk/) or [LeagueSharp](https://www.joduska.me/forum/user/380-madk/) forums?

**Comment by svenxxl** [comment]
Wrote u a pm @ L#

**Comment by madk** [comment]
Fixed in ba45899cd79260471e440f4b105b98a8f5026235
